
data:
  raw_data_path: "data/raw/diabetes.csv"
  processed_data_path: "data/processed/cleaned_diabetes.csv"

train_test_split:
  test_size: 0.2
  random_state: 2

scaling:
  method: "StandardScaler"

model:
  type: "NeuralNetwork"
  architecture:
    - layer: Dense
      units: 256
      activation: "relu"
      input_dim: 8
      kernel_regularizer: "l2"
    - layer: BatchNormalization
    - layer: Dropout
      rate: 0.3
    - layer: Dense
      units: 128
      activation: "relu"
      kernel_regularizer: "l2"
    - layer: BatchNormalization
    - layer: Dropout
      rate: 0.3
    - layer: Dense
      units: 64
      activation: "relu"
    - layer: Dense
      units: 1
      activation: "sigmoid"

optimizer:
  type: "Adam"
  learning_rate: 0.001

training:
  epochs: 100
  batch_size: 32
  early_stopping:
    monitor: "val_loss"
    patience: 10
